steps:
  - id: 'branch name'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
        echo "$BRANCH_NAME"
 
  - id: 'tf init'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          ls
          cd config
          terraform init
 
  - id: 'tf plan'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          cd config
          terraform init
          terraform plan
 
  - id: 'tf apply'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
            cd config
            terraform apply --auto-approve
              
         
 
options:
  logging: CLOUD_LOGGING_ONLY
