options:
  logging: CLOUD_LOGGING_ONLY  # Log to Google Cloud Logging (if you don't want to store logs in a bucket)

# Specify the logs bucket (uncomment and use your bucket's name)
 logs_bucket: gs://samaybucket/

steps:
  # Your build steps
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/terraform:$TAG', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/terraform:$TAG']

  - name: 'hashicorp/terraform'
    entrypoint: 'terraform'
    args: ['init']

  - name: 'hashicorp/terraform'
    entrypoint: 'terraform'
    args: ['apply', '-auto-approve']

images:
  - 'gcr.io/$PROJECT_ID/terraform:$TAG'
