options:
  logging: CLOUD_LOGGING_ONLY  # Log to Google Cloud Logging (you can remove this if you want to use Cloud Storage)

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/terraform:$TAG', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/terraform:$TAG']

  # Step 3: Run Terraform Init
  - name: 'hashicorp/terraform'
    entrypoint: 'terraform'
    args: ['init']

  # Step 4: Run Terraform Apply (this creates the VM or other resources)
  - name: 'hashicorp/terraform'
    entrypoint: 'terraform'
    args: ['apply', '-auto-approve']

images:
  - 'gcr.io/$PROJECT_ID/terraform:$TAG'
