steps:
  # Step 1: Build the Docker image with Terraform
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/terraform:latest', '.']

  # Step 2: Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/terraform:latest']

  # Step 3: Initialize Terraform
  - name: 'gcr.io/$PROJECT_ID/terraform:latest'
    entrypoint: 'terraform'
    args:
      - 'init'
      - '-backend-config=backend.hcl'  # Optional: Add this if you use remote backend like GCS.

  # Step 4: Apply Terraform configuration (optional)
  - name: 'gcr.io/$PROJECT_ID/terraform:latest'
    entrypoint: 'terraform'
    args:
      - 'apply'
      - '-auto-approve'  # Automatically approve any changes Terraform proposes

# Specify the image to be built and pushed
images:
  - 'gcr.io/$PROJECT_ID/terraform:latest'
